#!/usr/bin/env bash
# Verify the seeded database and prove the FR-04 / constraint rules hold.
# Usage (from the repository root, with `docker compose up -d db` running):
#     bash db/verify.sh
# Writes evidence/db-verification.txt and evidence/schema.sql
set -u
cd "$(dirname "$0")/.."
OUT=evidence/db-verification.txt
PW="${DB_ROOT_PASSWORD:-devpassword}"
mysql() { docker exec -i intellistock-db mysql -uroot -p"$PW" --table intellistock 2>&1 | grep -v "Using a password"; }

# expects the statement to be rejected; prints PASS with the database's own message
must_fail() {
    local label="$1" stmt="$2" result
    result=$(echo "$stmt" | mysql)
    if echo "$result" | grep -q "ERROR"; then
        echo "[PASS] $label"
    else
        echo "[FAIL] $label - statement was accepted"
    fi
    echo "       SQL: $stmt"
    echo "       -> $(echo "$result" | grep ERROR | head -1)"
    echo
}

{
    echo "IntelliStock - database verification"
    echo "================================================================"
    echo "Run at   : $(date '+%Y-%m-%d %H:%M')"
    echo "Database : MySQL $(echo 'SELECT VERSION();' | docker exec -i intellistock-db mysql -uroot -p"$PW" -N 2>/dev/null) in container intellistock-db"
    echo "Seed     : db/init/02-seed.sql, generated by db/seed/generate_seed.py"
    echo
    mysql < db/verify.sql
    echo
    echo "10. Rules the database itself enforces (each statement must be rejected)"
    echo
    must_fail "FR-04: a transaction cannot be edited" \
        "UPDATE \`Transaction\` SET QuantityChange = -1 WHERE TransactionId = 1;"
    must_fail "FR-04: a transaction cannot be deleted" \
        "DELETE FROM \`Transaction\` WHERE TransactionId = 1;"
    must_fail "FR-04: a stock item with history cannot be hard-deleted" \
        "DELETE FROM StockItem WHERE StockItemId = 1;"
    must_fail "A sale must reduce stock (positive sale rejected)" \
        "INSERT INTO \`Transaction\` (StockItemId, Type, QuantityChange, QuantityAfter, OccurredAt, RecordedByUserId) VALUES (1, 'Sale', 5, 10, NOW(), 1);"
    must_fail "Stock cannot go negative" \
        "UPDATE StockItem SET QuantityOnHand = -1 WHERE StockItemId = 1;"
    must_fail "FR-05: only one open alert per item" \
        "INSERT INTO Alert (StockItemId, Message, QuantityAtAlert, ReorderLevel, CreatedAt) SELECT StockItemId, 'duplicate', 0, 0, NOW() FROM Alert WHERE ResolvedAt IS NULL LIMIT 1;"
    must_fail "FR-02: email addresses are unique" \
        "INSERT INTO RegisteredUser (Email, PasswordHash, FullName, Role) VALUES ('nomvula@intellistock.test', 'x', 'Duplicate', 'BusinessOwner');"
    echo "Transaction count after the tests (unchanged from check 1):"
    echo "SELECT COUNT(*) AS \`rows\` FROM \`Transaction\`;" | mysql
} > "$OUT"

docker exec intellistock-db mysqldump -uroot -p"$PW" --no-data --triggers --skip-comments \
    --skip-add-drop-table intellistock 2>/dev/null | sed 's/ AUTO_INCREMENT=[0-9]*//' > evidence/schema.sql

cat "$OUT"
echo "Wrote $OUT and evidence/schema.sql"
