using IntelliStock.Api.Models;
using Microsoft.AspNetCore.Identity;

namespace IntelliStock.Api.Tests.Unit;

// FR-02 / D22: the seeded hashes are generated by Python (db/seed/generate_seed.py), so
// prove ASP.NET Core Identity's PasswordHasher accepts them - and rejects a wrong password.
[Trait("Category", "Unit")]
public class PasswordHashTests
{
    private static readonly PasswordHasher<RegisteredUser> Hasher = new();
    private static readonly BusinessOwner User = new();

    [Theory]
    [InlineData("nomvula@intellistock.test")]
    [InlineData("sipho@intellistock.test")]
    [InlineData("orders@ubuntu-wholesale.test")]
    public void Seeded_hash_verifies_with_the_seeded_test_password(string email)
    {
        var hash = SeedFile.PasswordHashFor(email);
        Assert.NotEmpty(hash);
        Assert.Equal(PasswordVerificationResult.Success,
            Hasher.VerifyHashedPassword(User, hash, SeedFile.TestPassword));
    }

    [Fact]
    public void Seeded_hash_rejects_a_wrong_password() =>
        Assert.Equal(PasswordVerificationResult.Failed,
            Hasher.VerifyHashedPassword(User, SeedFile.PasswordHashFor("nomvula@intellistock.test"), "wrong-password"));
}
